### PR TITLE
Nix flake and package definition

### PR DESCRIPTION
**Pull request by bddvlpr**
Nix packaging for reproducible builds. If you don't want this merged upstream, I will still maintain it on my fork. Cannot be published to [nixpkgs](https://github.com/nixos/nixpkgs) as it uses nightly features.

### CODE REVIEW

**Comment by raviqqe** [comment]
@bddvlpr Thank you for opening the PR. @tesujimath and I are thinking of contributing a Nix package to the official registry (See #225 for the discussion) as we now use stable Rust. Are you still using Schemat in any way? If you are willing to do that on our behalf, we appreciate it!

**Comment by tesujimath** [comment]
Ah, sorry for the misunderstanding, I was proposing to contribute a Nix flake in this repo.

I think the overhead of contributing to nixpkgs itself is significant and I'm not sure it's worth it.

Happy to make a PR to add a Nix flake here, but I think @bddvlpr has already done the work?

**Comment by bddvlpr** [comment]
I’ll revamp the nixpkgs package definition in a bit, shouldn’t take too long.

**Comment by raviqqe** [comment]
@bddvlpr Thank you so much!

**Pull request closed without merging**
